{
 "title": "Usage Insights - 1 - Overview",
 "description": "This is a Usage Insights dashboard expecting Grafana events in logfmt instead of json.",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_id",
    "label": "Instance",
    "query": {
     "query": "grafanacloud_grafana_instance_info{}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Usage Insight KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total usage insights events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Data sources Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count(sum by (datasourceId) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | error=\"\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" [$__range])))"
    }
   ]
  },
  {
   "title": "Dashboards Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(sum by (dashboardId) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\" } | logfmt |  error=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Users Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "count(sum by (userId) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Usage Insight Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Usage insights events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"data-request\" | error = \"\" [$__interval]))",
     "legendFormat": "Data Request successes"
    },
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"data-request\" | error != \"\" [$__interval]))",
     "legendFormat": "Data Requests errors"
    },
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"dashboard-view\" [$__interval]))",
     "legendFormat": "Dashboard views"
    }
   ]
  },
  {
   "title": "Top 10 dashboards",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (dashboardId,dashboardName,folderName) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"dashboard-view\" [$__range])))",
     "legendFormat": "{{dashboardName}}"
    }
   ]
  },
  {
   "title": "Top 10 data sources",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (datasourceName, datasourceId) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"data-request\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top 10 users",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"dashboard-view\" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Top 10 dashboards with errors",
   "type": "table",
   "description": "Click on the error count to view errors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum by (dashboardUid,dashboardName) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"data-request\" | error!=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top 10 data sources with errors",
   "type": "table",
   "description": "Click on the data source name or ID to view details, click on the error count to view errors",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum by (datasourceName, datasourceId) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"data-request\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" | error!=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top 10 users seeing errors",
   "type": "table",
   "description": "Click on the error count to view errors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\", instance_id=~\"$instance_id\"} | logfmt | eventName=\"data-request\" | error!=\"\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}