{
 "title": "Grafana Cloud Billing/Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_slug",
    "label": "Org",
    "query": "label_values(grafanacloud_org_info, org_slug)"
   },
   {
    "name": "org_id",
    "label": "Org ID",
    "query": "label_values(grafanacloud_org_info{org_slug=\"$org_slug\"}, org_id)"
   },
   {
    "name": "metrics_id",
    "label": "Metrics Id",
    "query": "label_values(grafanacloud_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "logs_id",
    "label": "Logs Id",
    "query": "label_values(grafanacloud_logs_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "traces_id",
    "label": "Traces Id",
    "query": "label_values(grafanacloud_traces_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "grafana_id",
    "label": "Grafana Id",
    "query": "label_values(grafanacloud_grafana_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "profiles_id",
    "label": "Profiles Id",
    "query": "label_values(grafanacloud_profiles_instance_info{org_id=~\"$org_id\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Billable Usage Overview", "type": "row" },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Metrics Series"
    }
   ]
  },
  {
   "title": "Total Metrics Series",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}",
     "legendFormat": "Billable Series"
    },
    {
     "expr": "grafanacloud_org_metrics_included_series{org_id=\"$org_id\"}",
     "legendFormat": "Included Series"
    },
    {
     "expr": "max(grafanacloud_instance_billable_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_metrics_overage{org_id=\"$org_id\"}) * on (id) group_left(name) grafanacloud_instance_info{org_id=\"$org_id\"}",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 15 },
   "options": {
    "content": "## About Billable Metrics Series\n\nThis panel displays the 95th percentile of your active series and samples, or data points, per minute (DPM) for this month so far.\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Metrics Ingestion Details** tab in the **Usage Drilldown** section at the bottom of this view.\n\nFor more information on cardinality and metrics usage, you can:\n\n- Learn to <a href=\"https://grafana.com/docs/grafana-cloud/metrics-control-usage/control-prometheus-metrics-usage/\" target=\"_blank\">Control Your Metrics Usage</a>\n- <a href=\"/d/cardinality-management\" target=\"_blank\">Locate your highest cardinality metrics</a> from your Cardinality Dashboards\n- <a href=\"/a/grafana-adaptive-metrics-app\" target=\"_blank\">Get started with our new Adaptive Metrics cost optimization tool</a>.\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "options": { "content": "---" } },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_logs_usage{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Logs Usage"
    }
   ]
  },
  {
   "title": "Total Logs Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_logs_usage{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "grafanacloud_org_logs_included_usage{org_id=\"$org_id\"}",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_logs_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"$org_id\"}) * on (id) group_left(name) grafanacloud_logs_instance_info{org_id=\"$org_id\"}",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 27 },
   "options": {
    "content": "## About Billable Logs\n\nYour **total billable logs usage** is calculated using the total number of ingested bytes generated by your logs for the entire month.\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Logs Ingestion Details** tab in the **Usage Drilldown** section at the bottom of this view.\n\nFor more information on logs usage, see:\n\n- <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/logs-control-usage/\" target=\"_blank\">Analyze and Understand your Logs usage</a>\n- <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/logs-control-usage/#reduce-unnecessary-log-usage\" target=\"_blank\">Reduce Unnecessary Logs usage</a>\n- <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/logs-billing/\" target=\"_blank\">About Grafana Cloud Logs Billing</a>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 }, "options": { "content": "---" } },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_usage{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Traces Usage"
    }
   ]
  },
  {
   "title": "Total Traces Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_usage{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "grafanacloud_org_traces_included_usage{org_id=\"$org_id\"}",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_traces_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_traces_overage{org_id=\"$org_id\"}) * on (id) group_left(name) grafanacloud_traces_instance_info{org_id=\"$org_id\"}",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 39 },
   "options": {
    "content": "## About Billable Traces\n\nYour **total billable traces usage** is calculated using the total number of ingested bytes generated by your traces this month.\n\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Usage Drilldown** section at the bottom of this view.\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 }, "options": { "content": "---" } },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users{org_id=\"$org_id\"}",
     "legendFormat": "Total Unique Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_grafana{org_id=\"$org_id\"} and grafanacloud_org_billable_users_oncall{org_id=\"$org_id\"} > 0",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_oncall{org_id=\"$org_id\"} > 0",
     "legendFormat": "OnCall Users"
    }
   ]
  },
  {
   "title": "Total Grafana Users Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users{org_id=\"$org_id\"}",
     "legendFormat": "Billable Users"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_overage{org_id=\"$org_id\"})",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_grafana_included_users{org_id=\"$org_id\"}",
     "legendFormat": "Included Users"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 51 },
   "options": {
    "content": "## About Billable Users\n\nYour **total billable grafana users** is determined by all <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/#billing-for-active-users\" target=\"_blank\">monthly active Grafana users</a> and their associated costs. Active users are only billed once per month across all your stacks.\n\nYou can dig deeper in the **Grafana Users Usage Details** tab in the **Usage Drilldown** section at the bottom of this view.\nFor Billable Incident/OnCall/IRM users, expand the **Incident Management and Resolution (IRM) Users** tab. For additional per user costs generated from an Enterprise plugin add-on, expand the **Enterprise Plugin Add-On** tab.\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 }, "options": { "content": "---" } },
  {
   "title": "Incident Response & Management (IRM) Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_irm_users{org_id=\"$org_id\"}",
       "legendFormat": "Current Billable IRM Users"
      }
     ]
    },
    {
     "title": "Total IRM Users",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 6, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_irm_users{org_id=\"$org_id\"}",
       "legendFormat": "Billable Users"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_irm_users_overage{org_id=\"$org_id\"})",
       "legendFormat": "Additional User Amount"
      },
      {
       "expr": "grafanacloud_org_irm_included_users{org_id=\"$org_id\"}",
       "legendFormat": "Included Users"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 63 },
     "options": {
      "content": "## About IRM Users\n\nYour Total Billable IRM Users panel reflects all active users of IRM services this month. A user is <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/irm-billing/\" target=\"_blank\">considered active</a> if they are included in OnCall schedules or escalation chains, or if they perform any of the actions below:\n- Changed status of alert group or OnCall configuration\n- Got paged or paged someone\n- Created, declared, edited, updated, or deleted an Incident\n"
     }
    }
   ]
  },
  {
   "title": "Enterprise Plugin Usage (Add-on)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users{org_id=\"$org_id\"}",
       "legendFormat": "Current Billable Enterprise Plugin Users"
      }
     ]
    },
    {
     "title": "Enterprise Plugin Users",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 6, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users{org_id=\"$org_id\"}",
       "legendFormat": "Billable Users"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_overage{org_id=\"$org_id\"})",
       "legendFormat": "Additional Usage Amount"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 63 },
     "options": {
      "content": "## About Enterprise Plugins\n\nUnder the Pro monthly subscription plan it is possible to add a single (1) Grafana Enterprise Plugin for use across your account. Once added, this comes at an additional cost of <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/#billing-for-active-users\" target=\"_blank\">$25 per Grafana active user</a>.\n\nIf you've added an Enterprise plugin, your Billable Enterprise Plugin Users panels displays your total number of Grafana active users and the additional aggregated cost at $25/user, this month so far.\n"
     }
    }
   ]
  },
  {
   "title": "k6 Virtual User Hours (VUh)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "VUh" } },
     "targets": [
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_usage{org_id=\"$org_id\"}",
       "legendFormat": "Current Billable VUh Usage"
      }
     ]
    },
    {
     "title": "Total Virtual User Hours (VUh)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 6, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "VUh" } },
     "targets": [
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_usage{org_id=\"$org_id\"}",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_overage{org_id=\"$org_id\"})",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_included_usage{org_id=\"$org_id\"}",
       "legendFormat": "Included Usage"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 63 },
     "options": {
      "content": "## About k6 Virtual User Hours\n\nYour Total k6 Billable Usage is based on Virtual User hours (VUh) used during your load tests. The Pro and Advanced plans include 1000 VUh/month with 30 day data retention for your test results.\n\nFor information on how we calculate VUh, please visit our <a href=\"https://grafana.com/docs/grafana-cloud/k6/get-started/vu-hours/\" target=\"_blank\">documentation</a>.\n"
     }
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "grafanacloud_org_profiles_usage{org_id=\"$org_id\"}",
       "legendFormat": "Current Billable Profiles Usage"
      }
     ]
    },
    {
     "title": "Total Profiles Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 6, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "grafanacloud_org_profiles_usage{org_id=\"$org_id\"}",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_profiles_overage{org_id=\"$org_id\"})",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_profiles_included_usage{org_id=\"$org_id\"}",
       "legendFormat": "Included Usage"
      },
      {
       "expr": "max(grafanacloud_profiles_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_profiles_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_profiles_overage{org_id=\"$org_id\"}) * on (id) group_left(name) grafanacloud_profiles_instance_info{org_id=\"$org_id\"}",
       "legendFormat": "Additional Usage Amount - {{ name }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 63 },
     "options": {
      "content": "## About Billable Profiles\n\nYour Total Billable Profiles Usage is calculated on the total number\nof ingested bytes generated by your profiles this month. Usage of\nGrafana Cloud Profiles is subject to <a\nhref=\"https://www.grafana.com/pricing\" target=\"_blank\">Grafana Cloud\nPricing</a> for Profiles.\n\n* <a href=\"https://grafana.com/docs/grafana-cloud/monitor-applications/profiles/\" target=\"_blank\">About Grafana Cloud Continuous Profiling</a>\n* <a href=\"https://grafana.com/blog/2023/08/09/grafana-cloud-profiles-for-continuous-profiling/\" target=\"_blank\">Blog: Unify your Observability signals with Grafana Cloud Profiles</a>\n"
     }
    }
   ]
  },
  {
   "title": "Graphite Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_graphite_metrics_billable_series{org_id=\"$org_id\"}",
       "legendFormat": "Current Graphite Metrics Usage"
      }
     ]
    },
    {
     "title": "Total Graphite Metrics Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "grafanacloud_org_graphite_metrics_billable_series{org_id=\"$org_id\"}",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_overage{org_id=\"$org_id\"})",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_graphite_metrics_included_series{org_id=\"$org_id\"}",
       "legendFormat": "Included Graphite Series"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\"><p style=\"text-align: center; font-size: 175%; padding: 0px; margin: 0px;\"><b>▼ Usage Drilldown ▼</b></p></div>"
   }
  },
  {
   "title": "Metrics Ingestion Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Active Series",
     "type": "timeseries",
     "description": "Shows:\n\n- Total active-series per managed Prometheus metrics service (GrafanaCloud Stack).\n- Active-series ingested in the Datadog format\n- Active-series ingested in the Influx format\n- Active-series per installed integration (with default job-name in Agent config)\n",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_active_series{id=~\"$metrics_id\"}) by (id) * on (id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "max(grafanacloud_instance_active_datadog_series{id=~\"$metrics_id\"} > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{ name }}: Datadog format"
      },
      {
       "expr": "max(grafanacloud_instance_active_influx_series{id=~\"$metrics_id\"} > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{ name }}: Influx format"
      },
      {
       "expr": "max(grafanacloud_instance_active_integration_series{id=~\"$metrics_id\"}) by (id, integration) * on (id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{name}}: {{integration}} intg."
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
     "options": {
      "content": "## About Metrics Active Series\n\nAn active series is a time series that receives new data points or samples. If you stop writing new datapoints to a time series, shortly afterwards it is no longer considered active. Learn more about <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/#active-series\" target=\"_blank\">Active Series</a>.\n\nYour Metrics Active Series panel graphs the total number of active series ingested to Grafana Cloud per push (scrape_interval) at a certain point in time. We recommend <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/optimize-scrape-interval/\" target=\"_blank\">setting that scrape_interval</a> to a resolution of once per minute (60s) to keep ingestion costs down. If you are sending series more frequently than once per minute, you will see this reflected in the rate of Data Points per Minute (DPM) in the two panel rows below.\n\n"
     }
    },
    {
     "title": "Highest Metrics DPM Stacks (top 3 stacks)",
     "type": "gauge",
     "description": "Shows up to 3 of your stacks, ordered by those with the greatest average DPM per active-series.\n\nThis value calculated at the current instant. ie. `now()`",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sort_desc(\n  max by(id, name) (\n    60 * grafanacloud_instance_samples_per_second{id=~\"$metrics_id\"}\n    / grafanacloud_instance_active_series{id=~\"$metrics_id\"}\n\n    * on(id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}\n  )\n)\n"
      },
      {
       "expr": "scalar(grafanacloud_org_metrics_included_dpm_per_series{org_id=\"$org_id\"})"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
     "options": {
      "content": "## About High DPM\n\nYour Highest Metrics DPM Stacks panel displays your top (or only) metrics ingestion instances and their current DPM (Data Points per Minute). Your plan has an included DPM rate, displayed numerically in green on the gauge panel. If you are sending metrics series at a rate per minute above that number (displayed center), you will see it metered in red. See the graph panel below for the active series ingestion per minute, over time.\n\nTo learn more about how this affects your billing, see: <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/\" target=\"_blank\">Active Series and DPM</a>. To control or change your DPM, check out: <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/\" target=\"_blank\">Changing your metrics scrape interval</a>.\n\n"
     }
    },
    {
     "title": "Metrics Active Series Ingestion Rate per Minute (DPM)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_samples_per_second{id=~\"$metrics_id\"} * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Metric Samples",
     "type": "timeseries",
     "description": "To learn more about these errors and dig into their potential causes, check out or Prometheus article: [Monitor Prometheus for ingest errors](https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/errors-monitoring/)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "si:/s" } },
     "targets": [
      {
       "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second{id=~\"$metrics_id\"}) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs Ingestion and Query Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second{id=~\"$logs_id\"}) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{id=~\"$logs_id\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Ingested Logs by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_logs_instance_bytes_received_per_second{id=~\"$logs_id\"} * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{id=~\"$logs_id\"} or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Log Samples",
     "type": "timeseries",
     "description": "To learn more about these errors and dig into potential causes check out our Loki article on [Request Validation & Rate-Limit Errors](https://grafana.com/docs/loki/latest/operations/request-validation-rate-limits/)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "si:/s" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second{id=~\"$logs_id\"}) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info{id=~\"$logs_id\"}",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    },
    {
     "title": "Logs Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_query_bytes:rate5m{id=~\"$logs_id\"}) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{id=~\"$logs_id\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Query Usage Ratio",
     "type": "bargauge",
     "description": "Shows the ratio of queried to ingested bytes over the selected time period on each of your stacks.",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_query_bytes:rate5m{id=~\"$logs_id\"}\n    ) [$__range:1m]\n  ) /\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_billable_bytes_received_per_second{id=~\"$logs_id\"}\n    ) [$__range:1m]\n  )\n) * on(id) group_left(name) grafanacloud_logs_instance_info{id=~\"$logs_id\"}\n",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio{org_id=\"$org_id\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 104 },
     "options": {
      "content": "\"Query Usage Ratio\" shows the ratio of queried to ingested bytes on each of your stacks.\nIf this ratio exceeds the \"Query Fair Usage Ratio\" configured for your plan, you will incur additional charges.\n\n\nLearn more: <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/logs-billing/#fair-use-policy-for-gbs-queried\" target=\"_blank\">Fair use policy for GBs queried</a>\n"
     }
    },
    {
     "title": "Query Fair Use Ratio",
     "type": "stat",
     "description": "The query fair usage ratio configured for your current plan",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 108 },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio{org_id=\"$org_id\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traces Ingestion Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second{id=~\"$traces_id\"}) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info{id=~\"$traces_id\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Ingested Traces by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_traces_instance_bytes_received_per_second{id=~\"$traces_id\"} * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info{id=~\"$traces_id\"} or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Spans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "si:/s" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m{id=~\"$traces_id\"}) by (id, reason) * on(id) group_left(name) grafanacloud_traces_instance_info{id=~\"$traces_id\"}",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grafana Users Usage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Grafana Users (last 30 days)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(grafanacloud_grafana_instance_active_user_count{id=~\"$grafana_id\"}) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info{id=~\"$grafana_id\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Profile Ingestion Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profiles Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_profiles_instance_bytes_received_per_second{id=~\"$profiles_id\"}) by (id) * on(id) group_left(name) grafanacloud_profiles_instance_info{id=~\"$profiles_id\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Ingested Profiles by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_profiles_instance_bytes_received_per_second{id=~\"$profiles_id\"} * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_profiles_instance_info{id=~\"$profiles_id\"} or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Profiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_profiles_instance_discarded_bytes_per_second{id=~\"$profiles_id\"}) by (id, reason) * on(id) group_left(name) grafanacloud_profiles_instance_info{id=~\"$profiles_id\"}",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Instance Usage Group Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active series per usage group",
     "type": "timeseries",
     "description": "The panel displays active series broken down by user-defined usage groups, and the number of active series not assigned to any group. This can be used for internal back-charging. Read the [documentation](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/analyze-costs/metrics-costs/define-usage-groups/) to learn more about this feature.\n\nPlease contact support to get this set up.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_active_usage_group_series{id=~\"$metrics_id\"}) by (id, group) * on (id) group_left(name) grafanacloud_instance_info{id=~\"$metrics_id\"}",
       "legendFormat": "{{name}}: group {{group}}"
      }
     ]
    }
   ]
  }
 ]
}