{
 "title": "Cloud Logs Export Insights",
 "description": "Cloud logs export insights",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Cloud Logs Export Insights\n\nCloud Logs Export Dashboard"
   }
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_logs_instance_cloud_logs_export_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timestamp of last synced file (UTC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_logs_instance_cloud_logs_export_last_synced_file_timestamp * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age of last synced file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - grafanacloud_logs_instance_cloud_logs_export_last_synced_file_timestamp",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs data copied in selected period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(grafanacloud_logs_instance_cloud_logs_export_exported_bytes[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Exported data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logs data exported in last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(grafanacloud_logs_instance_cloud_logs_export_exported_bytes[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs data exported in last 7d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(grafanacloud_logs_instance_cloud_logs_export_exported_bytes[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs data exported in last 30d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(grafanacloud_logs_instance_cloud_logs_export_exported_bytes[30d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}